# Generated by Django 3.2.16 on 2022-10-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=1.0),
        ),
    ]
