# Generated by Django 3.2.16 on 2022-10-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221026_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
